const val RELEASE_GROUP = "com.hendraanggrian.pages"
const val RELEASE_ARTIFACT = "minimal"
const val RELEASE_VERSION = "0.1"
const val RELEASE_DESCRIPTION = "Static webpage with toggleable dark mode for GitHub pages"
const val RELEASE_GITHUB = "https://github.com/hendraanggrian/$RELEASE_ARTIFACT-theme"